apiVersion: v1
kind: Service
metadata:
  name: angular-svc
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: angular-app 
  ports:
    - nodePort: 30000
      port: 80 
      targetPort: 80
