apiVersion: v1
kind: Pod
metadata:
  name: angular
  namespace: web-app
  labels:
    app: angular-app
spec:
  containers:
    - name: angular-cont
      image: mdnfiras/gmc-angular-front:latest
      imagePullPolicy: Always
      ports:
        - name: angular-port
          containerPort: 80
          protocol: TCP
