version: '2.3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    hostname: localhost
    #container_name: angular-app
    image: mdnfiras/gmc-angular-front:latest
    ports:
      - 8181:80

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
    environment:
      MONGODB_USER: "user1"
      MONGODB_DATABASE: "User"
      MONGODB_PASS: "pass1"
    volumes:
      - "./data:/data/db"

  express: #name of the second service
    image: mdnfiras/gmc-express-back:latest # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database
