apiVersion: v1
kind: Service
metadata:
  name: express-svc
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: express-app 
  ports:
    - nodePort: 30002
      port: 3000
      targetPort: 3000
