apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: web-app
  labels:
    app: mongo-app
spec:
  containers:
    - name: mongo-cont
      image: mongo
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root1
      - name: MONGO_INITDB_DATABASE
        value: users
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: pass1
      ports:
        - name: web
          containerPort: 27017
          protocol: TCP
